export const datas = [
  {
    id: 1,
    img: "https://images-na.ssl-images-amazon.com/images/I/71xOxM-mxpL._AC_UL600_SR600,400_.jpg",
    title: "Love",
    author: "Eric Carlé",
    price: "14$",
    h3: "#1",
  },
  {
    id: 2,
    img: "https://images-na.ssl-images-amazon.com/images/I/91m0hRAcxwL._AC_UL600_SR600,400_.jpg",
    title: "killers of the Flowers Moon",
    author: "David Grann",
    price: "8.99$",
    h3: "#2",
  },
  {
    id: 3,
    img: "https://images-na.ssl-images-amazon.com/images/I/913C+MR3S5L._AC_UL600_SR600,400_.jpg",
    title: "The Women",
    author: "Kristin Hannah",
    price: "27$",
    h3: "#3",
  },
  {
    id: 4,
    img: "https://images-na.ssl-images-amazon.com/images/I/813B9IVbjDL._AC_UL600_SR600,400_.jpg",
    title: "The Grift",
    author: "Clay Cane",
    price: "19.9$",
    h3: "#4",
  },
  {
    id: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/91n7p-j5aqL._AC_UL600_SR600,400_.jpg",
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    price: "24.99$",
    h3: "#5",
  },
  {
    id: 6,
    img: "https://images-na.ssl-images-amazon.com/images/I/810CZ-9akdL._AC_UL600_SR600,400_.jpg",
    title: "First Lie Wins",
    author: "Ashley Elston",
    price: "16.99$",
    h3: "#6",
  },
  {
    id: 7,
    img: "https://images-na.ssl-images-amazon.com/images/I/81AHTyq2wVL._AC_UL600_SR600,400_.jpg",
    title: "The Housemaid",
    author: "Freida McFadden",
    price: "8.11$",
    h3: "#7",
  },
  {
    id: 8,
    img: "https://images-na.ssl-images-amazon.com/images/I/71bVExi4yXL._AC_UL600_SR600,400_.jpg",
    title: "The Body Keeps The Score",
    author: "Bessel van der Kolk",
    price: "10.19$",
    h3: "#8",
  },
  {
    id: 9,
    img: "https://images-na.ssl-images-amazon.com/images/I/611X8GI7hpL._AC_UL600_SR600,400_.jpg",
    title: "The 48 Laws of Power ",
    author: "Robert Greene",
    price: "14.55$",
    h3: "#9",
  },
  {
    id: 10,
    img: "https://images-na.ssl-images-amazon.com/images/I/71dQACXhz6L._AC_UL600_SR600,400_.jpg",
    title: "Lessons in Chemistry",
    author: "Bonnie Garmus",
    price: "15.37$",
    h3: "#10",
  },
  {
    id: 11,
    img: "https://images-na.ssl-images-amazon.com/images/I/913KWawg9gL._AC_UL600_SR600,400_.jpg",
    title: "Bibble in 52 Weeks",
    author: "Dr Kimberly D. Moore",
    price: "8.99$",
    h3: "#11",
  },
  {
    id: 12,
    img: "https://images-na.ssl-images-amazon.com/images/I/81GuYRxyGEL._AC_UL600_SR600,400_.jpg",
    title: "Happy Valentine's Day, Mouse",
    author: "Lura Numeroff",
    price: "6.46$",
    h3: "#12",
  },
  {
    id: 6,
    img: "https://images-na.ssl-images-amazon.com/images/I/81NsX5gOJkL._AC_UL600_SR600,400_.jpg",
    title: "Taylor Swift",
    author: "Wendy loggia",
    price: "4.78$",
    h3: "#13",
  },
  {
    id: 12,
    img: "https://images-na.ssl-images-amazon.com/images/I/71W5-2NdNsL._AC_UL600_SR600,400_.jpg",
    title: "Haunting Adeline",
    author: "HD Carlton",
    price: "14.34$",
    h3: "#14",
  },
];
